[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-navy-and-ivory
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-navy-and-ivory
GtkTheme=oomox-navy-and-ivory
IconTheme=oomox-navy-and-ivory
MetacityTheme=oomox-navy-and-ivory
