#!/bin/bash
for i in {0..15}
do 
	convert -size 32x32 xc:$(xrdb -query | grep "color$i:" | cut -d ':' -f 2 | tr -d  '\t\n '
) color$(printf "%02d" $i).png
done
montage -tile 8x2 -geometry +0+0 -border 0 col*.png codeschool.png
rm color*.png
