#!/bin/bash
clear
NC='\033[0m'
farger=('\033[0;30m' '\033[0;31m' '\033[0;32m' '\033[0;33m' '\033[0;34m' '\033[0;35m' '\033[0;36m' '\033[0;37m' '\033[1;30m' '\033[1;31m' '\033[1;32m' '\033[1;33m' '\033[1;34m' '\033[1;35m' '\033[1;36m' '\033[1;37m')

fargenavn=('black' 'red' 'green' 'yellow' 'blue' 'magenta' 'cyan' 'white' 'bright black' 'bright red' 'bright green' 'bright yellow' 'bright blue' 'bright magenta' 'bright cyan' 'bright white')

variabel=0
while [ $variabel -lt 16 ]
do
#	echo -e "${NC} color"$variabel" - "${farger[2]}" ████ - ${NC}"
	xrdbfargen=$(xrdb -query | grep 'color'$variabel':')
	kunfargekode=$(echo $xrdbfargen | cut -d ':' -f 2 | tr -d '\t')
	paddvariabel=$(printf %02d $variabel)
	echo -e "${NC}color$paddvariabel - ${farger[$variabel]}████ - ${NC}$kunfargekode - ${fargenavn[$variabel]}"
	variabel=$((variabel+1))
done
